
/*
 * 
 */

package superbet.servicios.externo.provider;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.3.1
 * Sat Nov 19 19:51:52 GMT-02:00 2011
 * Generated source version: 2.3.1
 * 
 */


@WebServiceClient(name = "ServiceProviderImplService", 
                  wsdlLocation = "http://192.168.1.101:8080/SuperBetWsService/wsdl/SuperBetService.wsdl",
                  targetNamespace = "http://provider.externo.servicios.superbet/") 
public class ServiceProviderImplService extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://provider.externo.servicios.superbet/", "ServiceProviderImplService");
    public final static QName ServiceProviderImplPort = new QName("http://provider.externo.servicios.superbet/", "ServiceProviderImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://192.168.1.101:8080/SuperBetWsService/wsdl/SuperBetService.wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from http://192.168.1.101:8080/SuperBetWsService/wsdl/SuperBetService.wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public ServiceProviderImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ServiceProviderImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ServiceProviderImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public ServiceProviderImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE);
    }
    public ServiceProviderImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE);
    }

    public ServiceProviderImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName);
    }

    /**
     * 
     * @return
     *     returns ServiceProviderImpl
     */
    @WebEndpoint(name = "ServiceProviderImplPort")
    public ServiceProviderImpl getServiceProviderImplPort() {
        return super.getPort(ServiceProviderImplPort, ServiceProviderImpl.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ServiceProviderImpl
     */
    @WebEndpoint(name = "ServiceProviderImplPort")
    public ServiceProviderImpl getServiceProviderImplPort(WebServiceFeature... features) {
        return super.getPort(ServiceProviderImplPort, ServiceProviderImpl.class, features);
    }

}
