package superbet.servicios.externo.provider;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.3.1
 * Sat Nov 19 19:51:52 GMT-02:00 2011
 * Generated source version: 2.3.1
 * 
 */
 
@WebService(targetNamespace = "http://provider.externo.servicios.superbet/", name = "ServiceProviderImpl")
@XmlSeeAlso({ObjectFactory.class})
public interface ServiceProviderImpl {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "obtenerApuestasPagasUsuario", targetNamespace = "http://provider.externo.servicios.superbet/", className = "superbet.servicios.externo.provider.ObtenerApuestasPagasUsuario")
    @WebMethod
    @ResponseWrapper(localName = "obtenerApuestasPagasUsuarioResponse", targetNamespace = "http://provider.externo.servicios.superbet/", className = "superbet.servicios.externo.provider.ObtenerApuestasPagasUsuarioResponse")
    public java.util.List<superbet.servicios.externo.provider.DataGanador> obtenerApuestasPagasUsuario(
        @WebParam(name = "idUsuario", targetNamespace = "")
        java.lang.Integer idUsuario
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "listarEventosSimples", targetNamespace = "http://provider.externo.servicios.superbet/", className = "superbet.servicios.externo.provider.ListarEventosSimples")
    @WebMethod
    @ResponseWrapper(localName = "listarEventosSimplesResponse", targetNamespace = "http://provider.externo.servicios.superbet/", className = "superbet.servicios.externo.provider.ListarEventosSimplesResponse")
    public java.util.List<superbet.servicios.externo.provider.DataEvento> listarEventosSimples();

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "apostar", targetNamespace = "http://provider.externo.servicios.superbet/", className = "superbet.servicios.externo.provider.Apostar")
    @WebMethod
    @ResponseWrapper(localName = "apostarResponse", targetNamespace = "http://provider.externo.servicios.superbet/", className = "superbet.servicios.externo.provider.ApostarResponse")
    public java.lang.String apostar(
        @WebParam(name = "idUser", targetNamespace = "")
        java.lang.Integer idUser,
        @WebParam(name = "idEvento", targetNamespace = "")
        java.lang.Integer idEvento,
        @WebParam(name = "idResultado", targetNamespace = "")
        java.lang.Integer idResultado,
        @WebParam(name = "monto", targetNamespace = "")
        java.lang.Double monto
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "listarResultados", targetNamespace = "http://provider.externo.servicios.superbet/", className = "superbet.servicios.externo.provider.ListarResultados")
    @WebMethod
    @ResponseWrapper(localName = "listarResultadosResponse", targetNamespace = "http://provider.externo.servicios.superbet/", className = "superbet.servicios.externo.provider.ListarResultadosResponse")
    public java.util.List<superbet.servicios.externo.provider.DataResultado> listarResultados(
        @WebParam(name = "idEvento", targetNamespace = "")
        java.lang.Integer idEvento
    );

    @RequestWrapper(localName = "enviarResultadosGanadores", targetNamespace = "http://provider.externo.servicios.superbet/", className = "superbet.servicios.externo.provider.EnviarResultadosGanadores")
    @WebMethod
    @ResponseWrapper(localName = "enviarResultadosGanadoresResponse", targetNamespace = "http://provider.externo.servicios.superbet/", className = "superbet.servicios.externo.provider.EnviarResultadosGanadoresResponse")
    public void enviarResultadosGanadores(
        @WebParam(name = "arg0", targetNamespace = "")
        java.util.List<superbet.servicios.externo.provider.DataGanador> arg0
    );
}
